### ISSUE TITLE
JSHint directives - bad option

### ISSUE THREAD

**Issue by mikebel** [cjdev/jshint-mojo#22]
Hi there,

I am currently trying to use the JSHint directives to ignore certain parts of my code. Take the following code as an example:

var foo;
/* jshint -W116 */
if(foo == "") return;
/* jshint +W116 */

As per the JSHint documentation, the above directive is forcing JSHint to not raise a "Expected '{a}' and instead saw '{b}'." warning. However, when this code is processed by the jshint-mojo plugin, i receive the following error:

4,1: Bad option: '+W116'

The W116 warning is just an example, i have received the same error for other codes and the ignore directive. 

Any ideas why the plugin does not like the re-enabling of a warning?

Many thanks,

Mike

**Comment by slotties** [comment]
Works by now. Can be closed.
