### ISSUE TITLE
I can't find any releases greater than 1.3.0 in any released maven repository

### ISSUE THREAD

**Issue by johnkharvey** [cjdev/jshint-mojo#59]
Hello,

I'm trying to find 1.4.0, 1.5.0, or 1.6.0 releases via a maven repository.
Sadly, I'm having no luck.  Maven-central only has up to 1.3.0, as does OSS:
https://oss.sonatype.org/content/repositories/releases/com/cj/jshintmojo/jshint-maven-plugin/

Is there a way these new versions could be built and uploaded?  Or, if they have been, could you help to point me in the right direction?

Thanks!

**Comment by sparkoo** [comment]
Hi, same here :( any update ?

**Comment by kermit-the-frog** [comment]
Same here... :-(

**Comment by eggsby** [comment]
Paging @stupenrose

**Comment by guangweiqiao** [comment]
why not support the versions latter than 1.3.0 in maven repository?

**Comment by guangweiqiao** [comment]
Is there a simple way to upload the latest version to maven repository? I think many people are looking forward to this.

**Comment by iamplo** [comment]
any update on this? thanks

**Comment by Ruudieboy** [comment]
Any news?

**Comment by stupenrose** [comment]
Sorry, my focus has been elsewhere for a while now, and I'm something of a bottleneck for pushing CJ code to central ... maybe we can fix that.

At any rate, I've just released the latest code as 1.6.0 ... should hit the central repo as soon as the next oss.sonatype.org sync happens (sometime today I'd expect).
